### ISSUE TITLE
executing notes "below a line"

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#12]
I find it very useful to have a function in notespace, which re-computes all notes below a given line. Specially if this function is bound to a key in Emacs.

The implementation is very straight forward, just adding a filter to compute-this-note-space!

```
(defn compute-notes-below-line! [line]
  (read-notes-seq! *ns*)
  (->> *ns*
       (@ns->notes)
       (filter #(< line (get-in % [:metadata :line])))
       (run! (partial compute-note! *ns*)))
  [[:computed {:ns *ns*}]
   (render-this-ns!)])
```

I can make a PR, if you are interested

**Comment by daslu** [comment]
@behrica this is great!

I am now working on some major refactoring, that will break this code.
So, if it is ok, then let us wait for a few days before integrating this.

It would be great to have your opinion on this discussion of the planned change in evaluation semantics:
https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/evaluation.20semantics.20--.20suggested.20breaking.20change

Here we discuss our general plans:
https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/plan

Sorry some of the discussion is not here at the Issues ..

**Comment by behrica** [comment]
It's done.
