### ISSUE TITLE
only one note with the same content

### ISSUE THREAD

**Issue by genmeblog** [scicloj/notespace#2]
Sometimes there is a need to replace the same content more than once. 

```clojure
(note 1)
(note 1)

;; results

Expected only one element.
   {:elements
    [{:idx 175, :kind-and-forms-str "[:code [1]]"}
     {:idx 176, :kind-and-forms-str "[:code [1]]"}]}
```

**Comment by daslu** [comment]
@genmeblog thanks.

Version `"2.0.0-alpha2"` solved a bug that could be related.

Leaving this open eill we realize that it does not repeat.

Related discussion:
https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/multiple.20elements

**Comment by genmeblog** [comment]
working
