### ISSUE TITLE
add helper method to update "config"

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#23]
Currently I need to do something like this in my notespace to change configuration:

```clojure
 (reset! state/the-context
          (fx/swap-context
           @state/the-context
           #(-> %
                (assoc-in [:config :render-src?] true)))

```

I want to do something like:

``` clojure
(xxx/set-config-option! :render-src? true)
```

**Comment by daslu** [comment]
Thanks @behrica, this is part of the refactoring that I am about to push tonight.

Such changes will pass through the (cljfx-based) event system.

**Comment by daslu** [comment]
https://github.com/scicloj/notespace/blob/b39e5a29fa682fdf54f4cb67c0aadc23cd7cc33c/src/notespace/api.clj#L13

**Comment by behrica** [comment]
Perfect
