### ISSUE TITLE
notespace does not work on headless server

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#25]
JavaFX does not work on a servr without working X11 / DISPLAY.

I found a workaround from the cljfx package, namely adding this into project.clj:

```diff
diff --git a/project.clj b/project.clj
index e6d23b3..8ff5e10 100644
--- a/project.clj
+++ b/project.clj
@@ -26,4 +26,9 @@
                  [cljfx "1.7.5"]
                  [org.clojure/core.cache "1.0.207"]
                  [hawk "0.2.11"]
-                 [scicloj/gorilla-notes "0.5.0-SNAPSHOT"]])
+                 [scicloj/gorilla-notes "0.5.0-SNAPSHOT"]
+                 [org.testfx/openjfx-monocle "jdk-12.0.1+2"]]
+  
+
+  :jvm-opts ["-Dtestfx.robot=glass" "-Dglass.platform=Monocle" "-Dmonocle.platform=Headless" "-Dprism.order=sw"]
+  )
```
As well suggested here: https://stackoverflow.com/questions/27403410/headless-testing-with-javafx-and-testfx

**Comment by daslu** [comment]
Nice.

**Comment by behrica** [comment]
Not sure, if we want to "set" this properties somewhere in notespace itself.
If not, the user of notespace needed to do so.

**Comment by daslu** [comment]
Good question. In general, we need to discuss if Cljfx remains a dependency.

**Comment by daslu** [comment]
Version `3-beta4` removes the dependency on (the magnificent) cljfx, to avoid depending on JavaFX. The necessary parts were moved under the `notespace.cljfx.*` namespaces.
