### ISSUE TITLE
fix static rendering ?

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#30]
I noticed and saw the comment, that static rendering of graphs is not working.
But i does work on gorilla-notes, correct ?

Having this working, we could add a nice feature to notespce,
which is a "cli" function which renders a notespace into a html file, to be used from the shell.

It does work, except that the graphics don't render.

**Comment by daslu** [comment]
Do you mean static images in separate files, as discussed here?
https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/static.20files

Yes, that is important, but might not be easy to fix with the current rendering method.
I should address this at the gorilla-notes project, and it would require some systematic change in the way things work there.

**Comment by behrica** [comment]
> Do you mean static images in separate files, as discussed here?
> https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/static.20files
> 
No. Currently the vega plots for example do not appear in the static html,
but do work in the repl  + browser.

I get an error message in tghe java script console about "shadow" not defined.

**Comment by behrica** [comment]
Ok, plots in general work.
Vega seems to fail in render static html.

I make a simple example and a new issue, if needed

**Comment by behrica** [comment]
I added a vega example to the "experiment" notespace and it does work.
So there is something special with "my" notespace, on which static rendering of vega fails.

**Comment by behrica** [comment]
It does work on my report now. We can close it
