### ISSUE TITLE
investigate using math formulae support from gorilla-ui

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#45]
In the version of gorilla-ui we use 0.2.27 the MathJax seems to work well.
The math in the  "lein demo" of that version does work.

So the bug-report here:
https://github.com/pink-gorilla/gorilla-ui/issues/19

Does **not** apply to the version we use.

**Comment by behrica** [comment]
> Does **not** apply to the version we use.

I looked again, and there is as well te problem with 0.2.27. So the gorilla-ui demo has an issue in the "math" tab.

**Comment by behrica** [comment]
It is somehow an initialisation problem.

This javascript code is somehow not getting executed:
https://github.com/pink-gorilla/gorilla-ui/blob/v0.2.27/src/pinkgorilla/ui/ui/mathinit.js

If I execute this snippet (part of above) in the jacascript console in the browser:

```javascript
 var url = '/mathjax/tex-svg-full.js';
      //var url = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js';
      console.log ("loading mathjax from: " + url)
    var script = document.createElement('script');
    script.src = url
    script.async = true;
    document.head.appendChild(script);
```

And change tab and go back to "math" tab it works. (unless I reload page)

**Comment by behrica** [comment]
![image](https://user-images.githubusercontent.com/127361/101604694-925ed980-3a01-11eb-9e7d-b539907bd10d.png)

**Comment by behrica** [comment]
The call to it is commented out here:

https://github.com/pink-gorilla/gorilla-ui/blob/v0.2.27/src/pinkgorilla/ui/ui/math.cljs

**Comment by behrica** [comment]
Turning the comment here into code:
https://github.com/pink-gorilla/gorilla-ui/blob/3bb12b60fd520c0d5eaa968d8ba7ae916f0d743c/src/pinkgorilla/ui/ui/math.cljs#L14

makes it work for the demo.

Why was it commented ?

**Comment by behrica** [comment]
I belive I manged to this change to the "using-gorilla-notes", by recompleing / re-sintalling:

* gorilla-ui
* gorilla-notes

via "./node_modules/.bin/shadow-cljs compile xxx;lein install"

(keep in mind, that I am not really sure what I am doing here ...)

I get an other error message, when tries to load "mathjax" about missing highlights.

Can this be related to "mathjax" being explicitly bundled as older version, but not being a node module ?
So the dependencies resolution breaks ? (as highlight.js is not loaded automatically when loading mathjax)

**Comment by daslu** [comment]
@behrica thank you so much for this exploration, very enlightening.
I eventually added math support using KaTeX rather than MathJax, since for some reason I could not solve some problems with MathJax for static rendering.

**Comment by awb99** [comment]
this is fixed in todays release of gorilla-ui.

**Comment by awb99** [comment]
the issue was very simple to fix.

**Comment by daslu** [comment]
@awb99 nice, thanks for the update!

For reference, this is what we do in Notespace (more precisely, in the gorilla-notes project, which is its current rendering engine):
https://github.com/scicloj/gorilla-notes/blob/57e38010784f55d4843d4c2e54734628a2b5ad9b/src/gorilla_notes/components/math.cljs

.. and this is how we render math inside markdown:
https://github.com/scicloj/gorilla-notes/blob/57e38010784f55d4843d4c2e54734628a2b5ad9b/src/gorilla_notes/components/markdown.cljs

(The last part will probably have to change at some point -- we want the markdown text to be rendered as plain HTML rather than through React, so that we can have search engine optimization.)
