### ISSUE TITLE
(re)move logback.xml

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#52]
Notespace is a library, so should not have a logging configuration file "bundled" into its jar,
which we have right now.

If we need it for tests, it should go to test-resources

**Comment by daslu** [comment]
Thanks @behrica, you're right. I can look into it in the coming days.

**Comment by daslu** [comment]
Removed this file, as well as several other dependencies and obsolete namespaces.

https://github.com/scicloj/notespace/commit/dd76b1ce61e033b85634d623fb643981e3988cff
