### ISSUE TITLE
Ability to view the entire dataset in a scrollable format

### ISSUE THREAD

**Issue by ashimapanjwani** [scicloj/notespace#54]
Currently displays a maximum of 25 rows.

**Comment by daslu** [comment]
Thanks @ashimapanjwani !

The number of rows displayed by `notespace.kind/dataset` is determined by the printing of the dataset.

As we realized yesterday, the printing behavior can be controlled using the metadata of the dataset.

For example:
```clj
^kind/dataset
(-> {:x (map #(* 1000 %) (range 30))}
    tablecloth.api/dataset
    (vary-meta assoc :print-index-range (range 30)))
```
This dataset will have all 30 rows printed, and thus notespace will display all its rows.

See the documentation of the `tech.v3.dataset/dataset-data->str` function for these details:
https://github.com/techascent/tech.ml.dataset/blob/39065c938c2be5b85ca917dc75ecca40472636b7/src/tech/v3/dataset/print.clj#L93

----

Maybe we can suggest adding a convenience function to `tech.ml.dataset` that will set the metadata of a given dataset to print all rows. What do you think?

**Comment by daslu** [comment]
Closing this -- we'll solve that in tech.ml.dataset.
https://github.com/techascent/tech.ml.dataset/issues/195
https://github.com/techascent/tech.ml.dataset/issues/197
