### ISSUE TITLE
more direct support for rendering vega/vega-lite ?

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#6]
We can already render vega/ vega-lite with notespace by converting it to hiccup and the use note-as-hiccup.

Maybe it could be nice to go a step further and have a specific "note-vega", which could be the used like this.

(note-vega
  {:data     {:values (play-data "monkey" "slipper" "broom")}
   :encoding {:x     {:field "time" :type "ordinal"}
              :y     {:field "quantity" :type "quantitative"}
              :color {:field "item" :type "nominal"}}
   :width    400
   :height   400
   :mark     "line"}))

or maybe have a function in notespace somewhere:

(vega->hiccup m) and the use (note-as-hiccup)

Let me know, and I can make a PR

**Comment by daslu** [comment]
@behrica thank you so much for this idea.
Sorry for my slow reply, somehow I missed your message for your sometime.

An PR would be very welcome if you wish. Please tell me if I can help in any way.

This will bring us into some dilemmas about handling clojurescript/javascript dependencies, which is healthy to discuss at this stage, I guess.

**Comment by behrica** [comment]
regarding javascript dependencies:

My code assumes that the "vl2svg" is in the path and working.
Is this acceptable ?

We just needed to document it properly.

I just do the simplest possible PR and then we can discuss on it.

**Comment by daslu** [comment]
@behrica wonderful!
I'll look at your PR soon.

I'll add this to the default dependencies.

I guess at some stage it would be nice to add some logic that knows which js dependencies to include, based on some user config or on note kinds. Need to think about that a bit.

**Comment by daslu** [comment]
@behrica see also this related discussion:
https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/rendering.20charts.20in.20notespace/near/192911226

**Comment by genmeblog** [comment]
Just to let you know `vl2svg` doesn't work on WSL1 (Windows Subsystem Linux), `vg2svg` works.

**Comment by genmeblog** [comment]
To make it work on WSL instead of using vl2svg use `vl2vg` and then `vg2svg`

**Comment by behrica** [comment]
@genmeblog I am not a node.js experts, so I don't know how much I want to go into supporting different ways how vega and vega-cli is installed on a system.
I don't have access to WSL, so I can no try things out.

can you maybe tell me what happens of you run in an empty folder in WSL, the following command: 

```
npm install vega-cli vega-lite
```

For me (Arch Linux) it installs in   "node_modules/.bin" the following relevant scripts:

```
lrwxrwxrwx   1 carsten carsten   22 Apr  5 13:25 vg2pdf -> ../vega-cli/bin/vg2pdf
lrwxrwxrwx   1 carsten carsten   22 Apr  5 13:25 vg2png -> ../vega-cli/bin/vg2png
lrwxrwxrwx   1 carsten carsten   22 Apr  5 13:25 vg2svg -> ../vega-cli/bin/vg2svg
lrwxrwxrwx   1 carsten carsten   23 Apr  5 13:25 vl2pdf -> ../vega-lite/bin/vl2pdf
lrwxrwxrwx   1 carsten carsten   23 Apr  5 13:25 vl2png -> ../vega-lite/bin/vl2png
lrwxrwxrwx   1 carsten carsten   23 Apr  5 13:25 vl2svg -> ../vega-lite/bin/vl2svg
lrwxrwxrwx   1 carsten carsten   22 Apr  5 13:25 vl2vg -> ../vega-lite/bin/vl2vg
```

How does this look in WSL ?

**Comment by behrica** [comment]
Maybe it would make sense to create a specific "vega-cli" library in clojure,
which wraps the existing vega/vega-lite scripts and it could then take care of eventually existing differences between operation systems

**Comment by behrica** [comment]
I copied the existing code from oz into its own little 
package

https://github.com/behrica/vg-cli

**Comment by genmeblog** [comment]
@behrica forget, looks like my nodejs installation was broken.

Generally WSL is Ubuntu 18.04, so it looks exactly the same like on other Ubuntu.

**Comment by behrica** [comment]
Can be closed, as vega via darkstar is supported now

**Comment by daslu** [comment]
Thanks @behrica .

We are also planning to have interactive vega/vega-lite components using gorilla-ui
https://github.com/pink-gorilla/gorilla-ui
as explained here:
https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/renderer.20embedding
