### ISSUE TITLE
Discuss place for "notespace"

### ISSUE THREAD

**Issue by behrica** [scicloj/notespace#9]
You said in the intro:

> Creating a separate alternative would be the least desired outcome of the current project.

For me all the other options 

- Marginalia, 
- Org-Babel, 
- Gorilla REPL, 
- Pink Gorilla, 
- Clojuopyter, 
- Nextjournal, 
- Saite, 
- Oz.

are "inferior" compared to notespace.

This is because:

- I want to use Emacs + cider for code editing
- I want to work on a remote Emacs without using  X11, but see my "notebook" rendered in local browser (easy to achieve with notespace and port forwarding)
- I want to do data analysis, so I need text + plots together
- I want to use version control for my "notebooks"

So for me "notespace" is the first and only clojure notebook library having all the features I need.

Maybe "forces could be joined" to have a common underlying library of the tools you mentioned, including notespace.

In any case, I would like to see notespace being further developed.

**Comment by daslu** [comment]
Thanks @behrica , I would love to discuss further your view of this.

I feel the same about staying in Emacs. Note that Oz supports a similar workflow too.

Some of the above tools, e.g. Oz, Pink-Gorilla, can be used as ways to render notespaces in the browser (in a sense, better live-reload engines than the basic one used in notespace).
In a sense, this is what we are discussing at #7 -- @awb99 has designed a nice, simple API to support that.

**Comment by behrica** [comment]
Can be closed.
